apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    spring.application.name=registration-login-demo
    server.port=8081
    spring.datasource.url=jdbc:mysql://localhost:3306/Spring_Project_Demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=springuser
    spring.datasource.password=123456789
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.open-in-view=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    logging.level.org.springframework.web=DEBUG
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
    logging.level.org.hibernate.SQL=DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    spring.main.allow-bean-definition-overriding=true
    spring.datasource.hikari.maximum-pool-size=10
    spring.datasource.hikari.minimum-idle=5
    