apiVersion: v1
kind: Service
metadata:
  name: registration-login-demo
spec:
  type: NodePort
  selector:
    app: registration-login-demo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081